FROM 172.28.5.75/chit/nginx:1.11.4-alpine

COPY index.html /usr/share/nginx/html/index.html
COPY DockerFileEx.jpg /usr/share/nginx/html/DockerFileEx.jpg
COPY config.json  /root/.docker/config.json

EXPOSE 80
